### ISSUE TITLE
Custom Published mod pack item error

### ISSUE THREAD

**Issue by Zelioth** [sketchmacaw/MacawsModsIssues#228]
[19:25:30] [Render thread/ERROR]: Failed to read block texture at: (mcwdoors:block/oak_japanese2_door_upper, everycomp:block/mcaw/doors/oak_japanese2_door_upper_m)
java.io.IOException: java.util.NoSuchElementException: No value present
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:28) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.open(TextureImage.java:144) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleEntrySet.generateTextures(SimpleEntrySet.java:313) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicClientResources$8(SimpleModule.java:94) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicClientResources(SimpleModule.java:94) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$2(ClientDynamicResourcesHandler.java:54) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:49) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:52) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:85) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.m_5540_(DynResourceProvider.java:53) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10827_(SimpleReloadInstance.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.16.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:25) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	... 32 more
[19:25:30] [Render thread/ERROR]: Failed to read block texture at: (mcwdoors:block/oak_japanese2_door_lower, everycomp:block/mcaw/doors/oak_japanese2_door_lower_m)
java.io.IOException: java.util.NoSuchElementException: No value present
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:28) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.open(TextureImage.java:144) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleEntrySet.generateTextures(SimpleEntrySet.java:313) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicClientResources$8(SimpleModule.java:94) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicClientResources(SimpleModule.java:94) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$2(ClientDynamicResourcesHandler.java:54) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:49) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:52) ~[everycomp-1.19.2-2.0.6.jar%23278!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:85) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.m_5540_(DynResourceProvider.java:53) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10827_(SimpleReloadInstance.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23484!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.16.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.readImage(SpriteUtils.java:25) ~[moonlight-1.19.2-2.0.26.jar%23363!/:?]
	... 32 more

**Comment by Vatruvius** [comment]
I am experiencing this same issue, below is a Pastebin similar log errors for ease of reading.

[https://pastebin.com/m1uucnbr](https://pastebin.com/m1uucnbr)

**Comment by Eatham532** [comment]
I have noticed this in my logs before. This is a bug but does not affect starting the game.

**Comment by PatrickDeVries** [comment]
> I have noticed this in my logs before. This is a bug but does not affect starting the game.

For me it seems to be causing an array out of bounds exception which prevents me from joining a server

**Comment by Eatham532** [comment]
Hmmm. I dont have that ossue. Can you share your log and crash logs? Just upload the file dont paste it in.

**Comment by sketchmacaw** [comment]
Isn't it an issue with everycomp ?

**Comment by sketchmacaw** [comment]
I'm closing this since it looks to be an issue with everycomp, if it wouldn't be the case then I'll reopen this
