### ISSUE TITLE
Failed to create mod instance

### ISSUE THREAD

**Issue by CrashedCrash** [sketchmacaw/MacawsModsIssues#250]
**Describe the bug**
Cant loadup the game

**Mod name & Minecraft Version and Modloader**
Bridge / MC 1.19.2  / Forge 43.2.3

java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.3.jar%23173!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.3.jar%23172!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/CreativeModeTabEvent$Register
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2379!/:?]
	at com.mcwbridges.kikoz.MacawsBridges.<init>(MacawsBridges.java:40) ~[Bridges.jar%23163!/:1.0]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.CreativeModeTabEvent$Register
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2379!/:?]
	at com.mcwbridges.kikoz.MacawsBridges.<init>(MacawsBridges.java:40) ~[Bridges.jar%23163!/:1.0]
	... 14 more

**Comment by sketchmacaw** [comment]
Can you please test the most recent 2.0.7 bridges update for 1.19.2. It should be fixed now.
