### ISSUE TITLE
Last version of Macaw's Paths and Pavings not working with EveryCompat

### ISSUE THREAD

**Issue by bitmochibit** [sketchmacaw/MacawsModsIssues#347]
**Describe the bug**
Macaw's Paths and Pavings (last version) with EveryCompat causes the latest to fail the loading.

**Mod name & Minecraft Version and Modloader**
Minecraft 1.19.2
Forge 43.3.7
mcw-paths-1.0.4forge-mc1.19.2

**To Reproduce**
1. Install the latest version of Macaw's Paths and Pavings 
2. Install the latest or the second to last version of EveryCompat (I think also for other versions of EveryCompat)

**Additional context**
Here's the log from EveryCompat
[23Jan2024 22:53:41.300] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: everycomp, class net.mehvahdjukaar.every_compat.forge.EveryCompatForge
java.lang.NoSuchFieldError: PathsItemGroup
	at net.mehvahdjukaar.every_compat.modules.forge.mcaw.MacawPathsModule.<init>(MacawPathsModule.java:24) ~[everycomp-1.19.2-2.5.15.jar%23476!/:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:167) ~[everycomp-1.19.2-2.5.15.jar%23476!/:?]
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.<init>(EveryCompatForge.java:97) ~[everycomp-1.19.2-2.5.15.jar%23476!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.7.jar%23621!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.7.jar%23620!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
They need to update to work with the paths update, nothing I can do.
