### ISSUE TITLE
Server Crash on putting items inside any furniture item

### ISSUE THREAD

**Issue by hemangsrr** [sketchmacaw/MacawsModsIssues#362]
**Describe the bug**
When the Macaw's Furniture mod is used and any item is placed within any of it (cabinet, shelf, drawer etc) it crashed the game and the server

**Mod name & Minecraft Version and Modloader**
Macaw's Furniture.
MC Fabric 1.20.4. Running on an Exaroton server.

**To Reproduce**
1. Add any storage furniture item in the world
2. Try to place stuff within

**Additional context**
Server Crash Log
	[00:47:40] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_1735.method_48931(net.minecraft.class_1799)'
	at net.kikoz.mcwfurnitures.storage.FurnitureScreenHandler.method_7601(FurnitureScreenHandler.java:72) ~[mcw-furniture-3.2.2-mc1.20fabric.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java:394) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1640) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[00:47:40] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2024-03-27_00.47.40-server.txt

**Comment by hemangsrr** [comment]
This is working fine in Singleplayer world, with the same set of mods installed, but crashes when in server
Once I got an item to be placed within, but when i took it back out, it crashed

Adding mods list:
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/44643029/43a9c2c7-dfae-4e94-bd0a-68faaa63278a)

**Comment by sketchmacaw** [comment]
It is  because the file is for mc1.20 instead of 1.20.4 :) Just use the 1.20.4 one for fabric
