### ISSUE TITLE
Sitting in furniture chair crashes game with Fabric 1.20.4 modloader

### ISSUE THREAD

**Issue by jasonrubik** [sketchmacaw/MacawsModsIssues#395]
**Describe the bug**
Everything was working just fine, and then for no reason game crashed and now 1.20.4 world does not load at all.  Keeps crashing

**Mod name & Minecraft Version and Modloader**
mcw-furniture-3.2.2-mc1.20.4fabric.jar

![image](https://github.com/user-attachments/assets/f7f5fc38-df62-406f-9dc8-b58b8c735d38)

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
i have no idea how

**Screenshots**
![image](https://github.com/user-attachments/assets/d1922091-b92d-4bac-ad5f-7baefe7f7d86)

**Additional context**
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-07-27 08:31:49
Description: Unexpected error

java.lang.ClassCastException: class net.kikoz.mcwfurnitures.sittable.ChairEntity cannot be cast to class net.minecraft.class_1309 (net.kikoz.mcwfurnitures.sittable.ChairEntity and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57d5872c)
	at net.minecraft.class_329.handler$zzo000$dark$render(class_329.java:1488)
	at net.minecraft.class_329.method_1753(class_329.java:401)
	at net.minecraft.class_757.method_3192(class_757.java:912)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$zzo000$dark$render(class_329.java:1488)
	at net.minecraft.class_329.method_1753(class_329.java:401)

-- Uptime --
Details:
	JVM uptime: 105.455s
	Wall uptime: 78.597s
	High-res time: 74.287s
	Client ticks: 477 ticks / 23.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Demonator16'/160, l='ClientLevel', x=155.50, y=4.00, z=35.50]]
	Chunk stats: 1024, 565
	Level dimension: minecraft:overworld
	Level spawn location: World: (761,4,-618), Section: (at 9,4,6 in 47,0,-39; chunk contains blocks 752,-64,-624 to 767,319,-609), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,-64,-1024 to 1023,319,-513)
	Level time: 11030731 game time, 117126 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 100

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, programmer_art, fabric, ambientsounds, animation_overhaul, carryon, creativecore, dark, distanthorizons, dynamiclights, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, indium, iris, mcwfurnitures, modmenu, modmenu_programmer_art, necronomicon, sodium, sodium_programmer_art, starlight, file/Alacrity 1.21 v27.zip

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 973629208 bytes (928 MiB) / 2751463424 bytes (2624 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-4370 CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0412
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4531
	Graphics card #1 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c03
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 49013.50
	Virtual memory used (MB): 18506.10
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 262.24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 5.3.9
		animation_overhaul: Animation Overhaul 1.3.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		carryon: Carry On 2.1.3
		creativecore: CreativeCore 2.11.26
			net_neoforged_bus: bus 7.2.0
		dark: dark 1.0.0
		distanthorizons: Distant Horizons 2.1.2-a
		dynamiclights: Dynamic Lights 1.7.1+mod
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		indium: Indium 1.0.31+mc1.20.4
		iris: Iris 1.7.2+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		mcwfurnitures: Macaw's Furniture 3.2.2
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.2.0
			placeholder-api: Placeholder API 2.4.0-pre.1+1.20.4
		necronomicon: Necronomicon 1.4.2
		sodium: Sodium 0.5.8+mc1.20.4
		starlight: Starlight 1.1.3+fabric.f5dcd1a
	Loaded Shaderpack: ComplementaryReimagined_r5.2.2.zip
		Profile: HIGH (+6 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, programmer_art, fabric, file/Alacrity 1.21 v27.zip
	Current Language: en_us
	Locale: en_US
	CPU: 4x Intel(R) Core(TM) i3-4370 CPU @ 3.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Demonator16'/160, l='ServerLevel[Fallen Kingdom Castle + 2 Villag]', x=155.50, y=4.00, z=35.50]]
	Data Packs: vanilla, fabric, carryon (incompatible), dark, dynamiclights, fabric-convention-tags-v1, mcwfurnitures (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by jasonrubik** [comment]
I edited the level.dat file with NBTexplorer, and was able to delete the   RootVehicle id , as it was set to the chair  .  This fixed it and allowed me to load the world, with the mod still installed.  Then as a test, I right-clicked on a chair and CRASH !   I used to be able to sit in chairs with this same setup a few days ago.  No files were changed since then.

![image](https://github.com/user-attachments/assets/3a7ef219-8e38-4402-b329-8f5762f37dd7)
