### ISSUE TITLE
Reinforced metal door from Macaw's Doors causing crash and permanent instability MC 1.16.4

### ISSUE THREAD

**Issue by Barerock** [sketchmacaw/MacawsModsIssues#50]
MC: 1.16.4
Forge: 35.1.10
Macaw's Doors: 1.0.1

Description: I had a raid appear and decided to barricade myself in my cave with a Reinforced Metal door and a cobble stone wall. The first time I scrolled to the item it crashed the server instantly, but I wasn't able to capture the log, it looked similar to the one below. I restarted the server and placed the door and it decided to water log its bottom half, I placed it again and it waterlogged both halves, then repeated again after the 3rd time, then the server crashed again after I broke it and tried to replace it with blocks (which spammed a weird error that is also included in the log). I tried restarting, breaking blocks in the place the door used to be, but nothing would even drop on the ground after breaking it, and the error kept coming out in my console. Server crashed 2 more times with the same error, and I decided to report after trying to get other doors to function properly, which they didn't (would open half the door or all the door in intervals). Final crash happened when I was trying to place blocks back in the hole. The game never crashed fully, always sent me back to server list.

Summary: Reinforced Metal door had issues, I broke it, didn't give it back, errors caused more issues to happen and server crashed many times.

V Logs V
I believe this is the error that crashed it the first time, nothing above this segment is relevant, just world loading things and people leaving and dying. After those normal messages this error is what crashed it every time. I looked through my full console log and it doesn't include the crash parameters at all, all I could find was this latest debug log that showed what happened. It doesn't really clarify why the issue occurred, the door worked fine before (I put the EXACT door I placed here on a fridge to experiment with door styles and it was ayokay yesterday). And apologies for the weird spoiler format, it won't let me align the text with the original formatting, so all the "ats" are at the end of the previous line. Looks good on the Write screen but Preview shows it's messed up. Thanks a ton, the rest of your doors are lovely...

<details> [23Dec2020 16:10:47.174] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_271]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.world.server.ServerWorld.func_184138_a(ServerWorld.java:1017) ~[?:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:232) ~[?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraft.world.World.func_175656_a(World.java:283) ~[?:?]
	at net.minecraft.block.CactusBlock.func_225542_b_(CactusBlock.java:51) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:622) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:390) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more

Here is another I JUST captured directly from the console after breaking the iron door I had placed. This one just gets spammed and doesn't crash the server.

<details> [16:47:59] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraft.world.server.ServerWorld.func_184138_a(ServerWorld.java:1017) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.markAndNotifyBlock(World.java:232) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.block.DoublePlantBlock.func_241471_b_(DoublePlantBlock.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.DoorBlock.func_176208_a(SourceFile:97) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:196) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
        at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:245) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:149) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by Barerock** [comment]
I just discovered I also get errors spammed just opening regular trapdoors I'd already placed before this incident. Looks to be the same type of error.

**Comment by sketchmacaw** [comment]
Should be fixed in the 1.0.2 doors update. If not let me know.
