### ISSUE TITLE
Version check error

### ISSUE THREAD

**Issue by pjlasl** [sketchmacaw/MacawsModsIssues#70]
Version check error??

[08Mar2021 12:25:05.706] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [mcwfences] Starting version check at https://github.com/sketchmacaw/macawsmods/blob/master/fences.json
[08Mar2021 12:25:06.150] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:195) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_212]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?]

**Comment by sketchmacaw** [comment]
Will be fixed in the next update

**Comment by sketchmacaw** [comment]
Fixed in 1.0.2 for 1.18.1, later expect to fix it for 1.17 and 1.16.5.
